---
title: "KnowBR_estimation_and_process_completeness"
author: "Andreas Mehl"
date: "2024-11-20"
output: html_document
---

```{r}

  #Load data
  load("output/pams_for_completeness_v2.Rdata")
  
# Select data for half-degree resolution
  neotropical_epyphites_completeness <- for_comp[["half_degree"]]
  
 # Clean data by removing rows with missing latitude or longitude
  clean_data <- neotropical_epyphites_completeness %>%
    filter(!is.na(Latitude) & !is.na(Longitude))
  
  # Extract the relevant columns
  Latitude <- clean_data$Latitude
  Longitude <- clean_data$Longitude
  Species <- clean_data$Species 
  Counts <- clean_data$Counts 
  Family <- clean_data$family
  
  # Combine extracted data into a matrix
  result_matrix <- cbind(Species = clean_data$Species,
                         Longitude = clean_data$Longitude, 
                         Latitude = clean_data$Latitude, 
                         Counts = clean_data$Counts)
  
  # Convert the matrix to a data frame
  result_df <- as.data.frame(result_matrix)
  
 # Ensure numeric columns are properly formatted
  result_df$Longitude <- as.numeric(result_df$Longitude)
  result_df$Latitude <- as.numeric(result_df$Latitude)
  result_df$Counts <- as.numeric(result_df$Counts)
  
  # Run completeness analysis for all data
  data(adworld)
  KnowB(data = result_df,
      format="A",
      cell=30,
      curve= "Exponential",
      estimator=1,
      cutoff=0.01,
      cutoffCompleteness= 0.01,
      cutoffSlope= 1,
      largematrix=FALSE, 
      Area="World",
      colbg="transparent",
      colcon="transparent", 
      colf="black",
      pro=TRUE,
      inc=0.005,
      save="RData",
        file1="Completeness/Main30exp/Observed richness",
        file2="Completeness/Main30exp/List of species", 
        file3="Completeness/Main30exp/Species per site", 
        file4="Completeness/Main30exp/Estimators",
        file5="Completeness/Main30exp/Species per record", 
        file6="Completeness/Main30exp/Records", 
        file7="Completeness/Main30exp/Completeness", 
        file8="Completeness/Main30exp/Slope",
        file9="Completeness/Main30exp/Standard error of the estimators",
        na="NA", 
        dec=",", 
        row.names=FALSE,
        jpg=TRUE, 
        jpg1="Completeness/Main30exp/Observed richness.jpg", 
        jpg2="Completeness/Main30exp/Records.jpg", 
        jpg3="Completeness/Main30exp/Completeness.jpg",
        jpg4="Completeness/Main30exp/Slope.jpg",
        cex=1.5, pch=15, cex.labels=1.5, pchcol="red", ask=FALSE)
  
  # Initialize a list to store results for all families
  all_estimators <- list()
  
  # Load the saved estimators for all families
  load("Completeness/Main30exp/Estimators.RData")
  Estimators <- values
  
  # Add a column to specify the family or if is for all combined
  Estimators$Family <- "All_Families"
  all_estimators[["All_Families"]] <- Estimators
  
  # Define families of interest for individual analysis
  families <- c("Orchidaceae", "Bromeliaceae", "Araceae", "Piperaceae", "Polypodiaceae")
  
  
  # Run completeness analysis for each family individually
  for (var in families) {
    
      # Filter data for the current family
    family_data <- clean_data %>% filter(Family == var)
    
    # Combine into a matrix
    result_matrix <- cbind(Species = family_data$Species, 
                           Longitude = family_data$Longitude, 
                           Latitude = family_data$Latitude, 
                           Counts = family_data$Counts, 
                           Family = family_data$Family)
  
  # Convert the matrix to a data frame
  result_df <- as.data.frame(result_matrix)
  
  # Ensure numeric columns are properly formatted
  result_df$Longitude <- as.numeric(result_df$Longitude)
  result_df$Latitude <- as.numeric(result_df$Latitude)
  result_df$Counts <- as.numeric(result_df$Counts)
  
  # Run completeness analysis for the current family
  data(adworld)
    KnowB(data = result_df,
          format="A",
          cell=30,
          curve= "Exponential",
          estimator=1,
          cutoff=0.01,
          cutoffCompleteness= 0.01,
          cutoffSlope= 1,
          largematrix=FALSE, 
          Area="World", 
          save="RData",
          file4=paste0("Completeness/Main30exp/Estimators_", var))
  }
  
  # Load saved estimators for each family and store in the list
  for (var in families) {
  load(paste0("Completeness/Main30exp/Estimators_", var, ".RData"))
  values$Family <- var
  all_estimators[[var]] <- values
  }
  
  # Combine all family results into a single data frame and save
  EstimatorsAllFamilies <- bind_rows(all_estimators)
  save(EstimatorsAllFamilies, file="Completeness/Main30exp/EstimatorsAllFamilies.RData")
  



   load("Completeness/Main30exp/Estimators.RData")
 
   # Generate polar coordinate plots and save results
  SurveyQ(values, Longitude=values$Longitude, Latitude=values$Latitude, cell=30, Areas=NULL,
          variables=c("Slope","Completeness","Ratio"), completeness=c(50,90),
          slope=c(0.02,0.3), ratio=c(3,15), shape=NULL, shapenames=NULL,
          Area="World",main=NULL, PLOTP=NULL,
          PLOTB=NULL, POINTS=NULL, XLAB=NULL, YLAB=NULL, XLIM=NULL, YLIM=NULL,
          palette=c("blue","green","red"), COLOR=c("red","green","blue"), colm="black",
          labels=TRUE, sizelabels=1, LEGENDP=NULL, LEGENDM=NULL, file="Completeness/Main30exp/Polar coordinates.csv",
          na="NA", dec=",", row.names=FALSE, jpg=FALSE, filejpg="Completeness/Main30exp/Map.jpg")
  
  
```




Process completeness

```{r}
     # Load completeness estimators data
     data="Completeness/Main30exp/Estimators.RData"

     load(data)
     
     # Load country boundaries for mapping
     roads <- rnaturalearth::ne_countries(scale = 110,returnclass = "sf")
     
     # Process completeness data into categories
     datos <- values %>% as_tibble() %>%
       mutate(CompSlope = cut(Slope,breaks=c(0,0.02,0.1,0.3,1),labels=c("High","Fair","Insufficient","Poor"))) %>% 
       mutate(CompComp = cut(Completeness,breaks=c(0,50,75,90,100),labels=c("Poor","Insufficient","Fair","High"))) %>% 
       mutate(CompRatio = cut(Ratio,breaks=c(0,3,10,15,100),labels=c("Poor","Insufficient","Fair","High"))) %>% 
       mutate(Category = "Fair") %>% 
       mutate(Category = ifelse(CompSlope%in%c("High","Fair") & CompComp%in%c("High","Fair") & CompRatio%in%c("High","Fair"),"Fair",Category)) %>% 
       mutate(Category = ifelse(CompSlope%in%c("Insufficient","Poor") & CompComp%in%c("Insufficient","Poor") & CompRatio%in%c("Insufficient","Poor"),"Insufficient",Category)) %>% 
       mutate(Category = ifelse(CompSlope=="High" & CompComp=="High" & CompRatio=="High","High",Category)) %>% 
       mutate(Category = ifelse(CompSlope=="Poor" & CompComp=="Poor" & CompRatio=="Poor","Poor",Category)) %>% 
       mutate(Category = ifelse(is.na(Category),"Poor",Category))
     
     # Calculate total number of records
     datos %>% summarise(n=sum(Records)) %>% pull(n) -> final
     
     # Convert Category to a factor with specific levels
     datos <- datos %>% mutate(Category= factor(Category,levels=c("High","Fair","Insufficient","Poor")))
     
     
     
     # Create a map visualization
     ggplot() +
       geom_sf(data=roads,colour=NA,fill=adjustcolor(MetBrewer::met.brewer("Demuth",direction=-1)[1],alpha.f = 0.2),size=0.5) + xlim(c(-120, -30)) + ylim(-55, 30) + 
       theme(panel.background = element_blank(),panel.grid = element_blank(),axis.text = element_blank(),axis.ticks = element_blank(),panel.border = element_rect(fill=NA),legend.position = c(-.2,0.3),legend.background = element_rect(fill = NA),legend.key.size = unit(0.7, "cm"),legend.key.width = unit(0.6,"cm"),legend.text = element_text(family="EB Garamond",size=8),legend.title = element_text(family="EB Garamond"),legend.spacing = unit(0.1,"cm"),plot.title = element_text(family="EB Garamond",face="bold",size=18,hjust = 0.5),plot.subtitle = element_text(family="EB Garamond",size=12,hjust = 0.5)) +
       geom_tile(data=datos,aes(x=Longitude,y=Latitude,fill=Category)) +
       scale_fill_manual(values=MetBrewer:::met.brewer("Hiroshige",n=12)[c(1,4,8,12)],name="") +
       labs(x="",y="",title="Digital botanical knowledge in the Neotropics",subtitle=paste0(formatC(final,format="f",digits = 0, big.mark=",")," occurrence records ")) +
       NULL
  
     
     
     
      save(datos,file = here("interim/KnowB_datos.Rdata"))
```

Repeating the steps of this chunk in the next


For countrys 15 arc minutes
```{r}
load("output/pams_for_completeness_v2.Rdata")
  
  
  neotropical_epyphites_completeness <- for_comp[["fifth_degree"]]
  
  clean_data <- neotropical_epyphites_completeness %>%
    filter(!is.na(Latitude) & !is.na(Longitude))
  
  # Extract the relevant columns
  Latitude <- clean_data$Latitude
  Longitude <- clean_data$Longitude
  Species <- clean_data$Species 
  Counts <- clean_data$Counts 
  Family <- clean_data$family
  
  result_matrix <- cbind(Species = clean_data$Species,
                         Longitude = clean_data$Longitude, 
                         Latitude = clean_data$Latitude, 
                         Counts = clean_data$Counts)
  
  # Convert the matrix to a data frame
  result_df <- as.data.frame(result_matrix)
  
  # Ensure columns are numeric where needed
  result_df$Longitude <- as.numeric(result_df$Longitude)
  result_df$Latitude <- as.numeric(result_df$Latitude)
  result_df$Counts <- as.numeric(result_df$Counts)
  
  # Run completeness analysis for all data
  data(adworld)
  KnowB(data = result_df,
      format="A",
      cell=15,
      curve= "Exponential",
      estimator=1,
      cutoff=0.01,
      cutoffCompleteness= 0.01,
      cutoffSlope= 1,
      largematrix=FALSE, 
      Area="World",
      colbg="transparent",
      colcon="transparent", 
      colf="black",
      pro=TRUE,
      inc=0.005,
      save="RData",
        file1="Completeness/Main15exp/Observed richness",
        file2="Completeness/Main15exp/List of species", 
        file3="Completeness/Main15exp/Species per site", 
        file4="Completeness/Main15exp/Estimators",
        file5="Completeness/Main15exp/Species per record", 
        file6="Completeness/Main15exp/Records", 
        file7="Completeness/Main15exp/Completeness", 
        file8="Completeness/Main15exp/Slope",
        file9="Completeness/Main15exp/Standard error of the estimators",
        na="NA", 
        dec=",", 
        row.names=FALSE,
        jpg=TRUE, 
        jpg1="Completeness/Main15exp/Observed richness.jpg", 
        jpg2="Completeness/Main15exp/Records.jpg", 
        jpg3="Completeness/Main15exp/Completeness.jpg",
        jpg4="Completeness/Main15exp/Slope.jpg",
        cex=1.5, pch=15, cex.labels=1.5, pchcol="red", ask=FALSE)
  
  # list to store the results
  all_estimators <- list()
  
  load("Completeness/Main15exp/Estimators.RData")
  Estimators <- values
  
  # Add a column to specify the family or if is for all combined
  Estimators$Family <- "All_Families"
  all_estimators[["All_Families"]] <- Estimators
  
  families <- c("Orchidaceae", "Bromeliaceae", "Araceae", "Piperaceae", "Polypodiaceae")
  
  for (var in families) {
    family_data <- clean_data %>% filter(Family == var)
    
    # Combine into a matrix
    result_matrix <- cbind(Species = family_data$Species, 
                           Longitude = family_data$Longitude, 
                           Latitude = family_data$Latitude, 
                           Counts = family_data$Counts, 
                           Family = family_data$Family)
  
  # Convert the matrix to a data frame
  result_df <- as.data.frame(result_matrix)
  
  # Ensure columns are numeric where needed
  result_df$Longitude <- as.numeric(result_df$Longitude)
  result_df$Latitude <- as.numeric(result_df$Latitude)
  result_df$Counts <- as.numeric(result_df$Counts)
  
  data(adworld)
    KnowB(data = result_df,
          format="A",
          cell=15,
          curve= "Exponential",
          estimator=1,
          cutoff=0.01,
          cutoffCompleteness= 0.01,
          cutoffSlope= 1,
          largematrix=FALSE, 
          Area="World", 
          save="RData",
          file4=paste0("Completeness/Main15exp/Estimators_", var))
  }
  
  # Cargar archivos por familia fuera del loop
  for (var in families) {
  load(paste0("Completeness/Main15exp/Estimators_", var, ".RData"))
  values$Family <- var
  all_estimators[[var]] <- values
  }
  
  # Bind rows and save
  EstimatorsAllFamilies <- bind_rows(all_estimators)
  save(EstimatorsAllFamilies, file="Completeness/Main15exp/EstimatorsAllFamilies.RData")
  
  


   load("Completeness/Main15exp/Estimators.RData")
 
   
  SurveyQ(values, Longitude=values$Longitude, Latitude=values$Latitude, cell=15, Areas=NULL,
          variables=c("Slope","Completeness","Ratio"), completeness=c(50,90),
          slope=c(0.02,0.3), ratio=c(3,15), shape=NULL, shapenames=NULL,
          Area="World",main=NULL, PLOTP=NULL,
          PLOTB=NULL, POINTS=NULL, XLAB=NULL, YLAB=NULL, XLIM=NULL, YLIM=NULL,
          palette=c("blue","green","red"), COLOR=c("red","green","blue"), colm="black",
          labels=TRUE, sizelabels=1, LEGENDP=NULL, LEGENDM=NULL, file="Completeness/Main15exp/Polar coordinates.csv",
          na="NA", dec=",", row.names=FALSE, jpg=FALSE, filejpg="Completeness/Main15exp/Map.jpg")
  
  
```



Process completeness for countrys 15 arc minutes
```{r}

     data="Completeness/Main15exp/Estimators.RData"

     load(data)
     
     roads <- rnaturalearth::ne_countries(scale = 110,returnclass = "sf")
     
     datos <- values %>% as_tibble() %>%
       mutate(CompSlope = cut(Slope,breaks=c(0,0.02,0.1,0.3,1),labels=c("High","Fair","Insufficient","Poor"))) %>% 
       mutate(CompComp = cut(Completeness,breaks=c(0,50,75,90,100),labels=c("Poor","Insufficient","Fair","High"))) %>% 
       mutate(CompRatio = cut(Ratio,breaks=c(0,3,10,15,100),labels=c("Poor","Insufficient","Fair","High"))) %>% 
       mutate(Category = "Fair") %>% 
       mutate(Category = ifelse(CompSlope%in%c("High","Fair") & CompComp%in%c("High","Fair") & CompRatio%in%c("High","Fair"),"Fair",Category)) %>% 
       mutate(Category = ifelse(CompSlope%in%c("Insufficient","Poor") & CompComp%in%c("Insufficient","Poor") & CompRatio%in%c("Insufficient","Poor"),"Insufficient",Category)) %>% 
       mutate(Category = ifelse(CompSlope=="High" & CompComp=="High" & CompRatio=="High","High",Category)) %>% 
       mutate(Category = ifelse(CompSlope=="Poor" & CompComp=="Poor" & CompRatio=="Poor","Poor",Category)) %>% 
       mutate(Category = ifelse(is.na(Category),"Poor",Category))
     
     datos %>% summarise(n=sum(Records)) %>% pull(n) -> final
     
     datos <- datos %>% mutate(Category= factor(Category,levels=c("High","Fair","Insufficient","Poor")))
     
     
     
     
     ggplot() +
       geom_sf(data=roads,colour=NA,fill=adjustcolor(MetBrewer::met.brewer("Demuth",direction=-1)[1],alpha.f = 0.2),size=0.5) + xlim(c(-120, -30)) + ylim(-55, 30) + 
       theme(panel.background = element_blank(),panel.grid = element_blank(),axis.text = element_blank(),axis.ticks = element_blank(),panel.border = element_rect(fill=NA),legend.position = c(-.2,0.3),legend.background = element_rect(fill = NA),legend.key.size = unit(0.7, "cm"),legend.key.width = unit(0.6,"cm"),legend.text = element_text(family="EB Garamond",size=8),legend.title = element_text(family="EB Garamond"),legend.spacing = unit(0.1,"cm"),plot.title = element_text(family="EB Garamond",face="bold",size=18,hjust = 0.5),plot.subtitle = element_text(family="EB Garamond",size=12,hjust = 0.5)) +
       geom_tile(data=datos,aes(x=Longitude,y=Latitude,fill=Category)) +
       scale_fill_manual(values=MetBrewer:::met.brewer("Hiroshige",n=12)[c(1,4,8,12)],name="") +
       labs(x="",y="",title="Digital botanical knowledge in the Neotropics",subtitle=paste0(formatC(final,format="f",digits = 0, big.mark=",")," occurrence records ")) +
       NULL
  
     
     
     
      save(datos,file = here("interim/KnowB_datos_15arc.Rdata"))
```

